branches:
  only:
  - master

clone_depth: 5

version: '{build}'

stack: python 3.9

environment:
  matrix:
#     - APPVEYOR_BUILD_WORKER_IMAGE: macOS
#     - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
#     - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
#       CC: clang
#       CXX: clang++
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      PYTHON: C:/Python39-x64
      PATH: $(PYTHON)/Scripts/;$(PATH)

install:
  - pip install conan
#   - sh: if [ "${APPVEYOR_BUILD_WORKER_IMAGE}" == "Ubuntu2004" ]; then sudo apt install -y libgl-dev libglu1-mesa-dev; fi

build_script:
  - sh: cd ${APPVEYOR_BUILD_FOLDER}
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - sh: conan profile new default --detect
  - sh: if [ "${APPVEYOR_BUILD_WORKER_IMAGE}" == "Ubuntu2004" ]; then conan profile update settings.compiler.libcxx=libstdc++11 default; fi
  - conan config set general.revisions_enabled=1
  - conan remote add bincrafters https://bincrafters.jfrog.io/artifactory/api/conan/public-conan
  - conan remote add icebreakersentertainment https://artifactory.icebreakersentertainment.com/artifactory/api/conan/icebreakersentertainment
  - conan install .. --build=missing
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="conan_paths.cmake" -DICSCRIPT_BUILD_BENCHMARKS=1 -DICSCRIPT_BUILD_TESTS=1 -DICSCRIPT_BUILD_AS_LIBRARY=1 ..
  - sh: make
  - cmd: msbuild /p:Configuration=Release ice_script.sln

test_script:
  - ctest
