branches:
  only:
  - master

clone_depth: 5

version: '{build}'

stack: python 3.9

environment:
  matrix:
#     - APPVEYOR_BUILD_WORKER_IMAGE: macOS
#     - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      CC: clang-14
      CXX: clang++-14
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      PYTHON: C:/Python39-x64
      PATH: $(PYTHON)/Scripts/;$(PATH)

install:
  - pip install conan

build_script:
#   - sh: sudo ln -s /usr/bin/clang++-14 /usr/bin/clang++
#   - sh: sudo ln -s /usr/bin/clang-14 /usr/bin/clang
#   - sh: sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-14  20
#   - sh: sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-14  20
  - sh: cd ${APPVEYOR_BUILD_FOLDER}
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - sh: conan profile new default --detect
  - sh: if [ "${APPVEYOR_BUILD_WORKER_IMAGE}" == "Ubuntu2004" ]; then conan profile update settings.compiler.libcxx=libstdc++11 default; fi
  - conan config set general.revisions_enabled=1
  - conan remote add bincrafters https://bincrafters.jfrog.io/artifactory/api/conan/public-conan
  - conan remote add icebreakersentertainment https://artifactory.icebreakersentertainment.com/artifactory/api/conan/bincrafters_proxy --insert
  - conan remote add icebreakersentertainment https://artifactory.icebreakersentertainment.com/artifactory/api/conan/center.conan.io_proxy --insert
  - conan remote add icebreakersentertainment https://artifactory.icebreakersentertainment.com/artifactory/api/conan/icebreakersentertainment --insert
#   - conan install .. --build=missing
  - conan install ..
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="conan_paths.cmake" -DICESCRIPT_BUILD_BENCHMARKS=1 -DICESCRIPT_BUILD_TESTS=1 -DICESCRIPT_BUILD_AS_LIBRARY=1 ..
  - sh: make
  - cmd: msbuild /p:Configuration=Release ice_script.sln

test_script:
  - ctest
